[package]
name = "refactor_platform_rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "api", "entity", "migration"]

[dependencies]
api = { path = "api" }
clap = { version = "4.4.6", features = ["cargo", "derive", "env"] }

