[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
axum-login = "0.12.0"
serde = { version = "1", features = ["derive"] }


[dependencies.sea-orm]
version = "0.12"
