//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub mod prelude;

pub mod actions;
pub mod agreements;
pub mod coaching_sessions;
pub mod notes;
pub mod overarching_goals;
pub mod seaql_migrations;
