[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity_api = { path = "../entity_api" }
axum = "0.6.20"
tower-http = { version = "0.4.4", features = ["fs"] }
service = { path = "../service" }
