[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity = { path = "../entity" }
entity_api = { path = "../entity_api" }
service = { path = "../service" }

axum = "0.7.2"
log = "0.4"
tower-http = { version = "0.5.0", features = ["fs"] }
serde_json = "1.0.107"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35.0", features = ["full"] }
chrono = { version = "0.4.31", features = ["serde"] }
axum-extra = { version = "0.9.1", features = ["typed-header"] }

[dependencies.sea-orm]
version = "0.12" # sea-orm version
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    "sqlx-postgres"
]

[features]
mock = ["sea-orm/mock"]

[dev-dependencies]
anyhow = "1.0.76"
reqwest = "0.11.23"
