[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity = { path = "../entity" }
entity_api = { path = "../entity_api" }
service = { path = "../service" }

axum = "0.7.2"
log = "0.4"
tower-http = { version = "0.5.0", features = ["fs"] }
serde_json = "1.0.107"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35.0", features = ["full"] }

[dependencies.sea-orm]
version = "0.12.3" # sea-orm version
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    "sqlx-postgres"
]

[dev-dependencies]
anyhow = "1.0.75"
reqwest = "0.11.22"
